### ISSUE TITLE
Add LayZSpa to HomeAssistant no climate entity

### ISSUE THREAD

**Issue by cardroidmuhely** [cdpuk/ha-bestway#56]
## Bestway device

 Home Assistant 2023.8.2 Supervisor 2024.04.0 Operating System 10.4 Kezelőfelület 20230802.0 - latest 
LayZSpa Helsinki

## Describe the bug

After i added my Helsinki to Home Assistant, no climate entity.

## Logs

Ez a hiba egy egyéni integrációból lett származtatva.

Logger: homeassistant.loader
Source: custom_components/bestway/climate.py:25
Integration: Bestway (documentation, issues)
First occurred: 15:04:52 (2 occurrences)
Last logged: 15:22:44

Unexpected exception importing platform custom_components.bestway.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bestway/climate.py", line 25, in <module>
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

**Comment by cdpuk** [comment]
The integration is not tested or supported on old Home Assistant versions, which seems to be the problem here. I suggest upgrading to the latest, but you can also try old versions of the integration as an alternative.
