### ISSUE TITLE
Havana Airjet device climate missing

### ISSUE THREAD

**Issue by pozsothereal** [cdpuk/ha-bestway#68]
Hi,

From the app i can control climate temp and switch on/off the heating, but in HA the climate entity is missing and the on/off switch as well.

Thanks!

**Comment by pozsothereal** [comment]
1st error:

Logger: homeassistant.loader
Source: custom_components/bestway/climate.py:25
Integration: Bestway (documentation, issues)
First occurred: 17:39:44 (1 occurrences)
Last logged: 17:39:44

Unexpected exception importing platform custom_components.bestway.climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bestway/climate.py", line 25, in <module>
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 783, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF




2nd error:
Logger: homeassistant.setup
Source: setup.py:379
First occurred: 17:39:44 (1 occurrences)
Last logged: 17:39:44

Unable to prepare setup for platform bestway.climate: Platform not found (Exception importing custom_components.bestway.climate).

**Comment by pozsothereal** [comment]
Hah, commented out line 25 26 in climate.yaml and it just works!:D
_CLIMATE_FEATURES = (
    ClimateEntityFeature.TARGET_TEMPERATURE
    # | ClimateEntityFeature.TURN_OFF
    # | ClimateEntityFeature.TURN_ON
)

**Comment by pozsothereal** [comment]
Solved

**Comment by cdpuk** [comment]
Possible old version of HA?
