### ISSUE TITLE
Lot of errors

### ISSUE THREAD

**Issue by Soltinioo** [cdpuk/ha-bestway#69]
integration works. but generates a lot of errors. what can be done about it?

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.bestway.coordinator
Źródło: helpers/update_coordinator.py:344
integracja: Bestway (dokumentacja, Problemy)
Pierwsze zdarzenie: 26 lipca 2024 10:56:58 (130 zdarzenia)
Ostatnio zalogowany: 08:54:44

Error fetching Bestway API data: Error communicating with API: 502, message='Bad Gateway', url=URL('https://usapi.gizwits.com/app/bindings')
Error fetching Bestway API data: Error communicating with API: 502, message='Bad Gateway', url=URL('https://usapi.gizwits.com/app/devdata/vzWm6Jcv5NxUL20M3M8KwC/latest')
Error fetching Bestway API data: Error communicating with API:
Error fetching Bestway API data: Error communicating with API: 500, message='INTERNAL SERVER ERROR', url=URL('https://usapi.gizwits.com/app/devdata/vzWm6Jcv5NxUL20M3M8KwC/latest')

-----
Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.bestway.coordinator
Źródło: custom_components/bestway/coordinator.py:37
integracja: Bestway (dokumentacja, Problemy)
Pierwsze zdarzenie: 26 lipca 2024 11:29:29 (67 zdarzenia)
Ostatnio zalogowany: 08:54:44

Data update failed
Traceback (most recent call last):
  File "/config/custom_components/bestway/bestway/api.py", line 76, in _raise_for_status
    api_error = await response.json()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 79, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://usapi.gizwits.com/app/devdata/vzWm6Jcv5NxUL20M3M8KwC/latest')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/bestway/coordinator.py", line 37, in _async_update_data
    return await self.api.fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bestway/bestway/api.py", line 168, in fetch_data
    latest_data = await self._do_get(
                  ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bestway/bestway/api.py", line 436, in _do_get
    await _raise_for_status(response)
  File "/config/custom_components/bestway/bestway/api.py", line 78, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://usapi.gizwits.com/app/devdata/vzWm6Jcv5NxUL20M3M8KwC/latest')

---

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.bestway.coordinator
Źródło: custom_components/bestway/coordinator.py:36
integracja: Bestway (dokumentacja, Problemy)
Pierwsze zdarzenie: 26 lipca 2024 10:56:58 (58 zdarzenia)
Ostatnio zalogowany: 08:39:45

Data update failed
Traceback (most recent call last):
  File "/config/custom_components/bestway/bestway/api.py", line 76, in _raise_for_status
    api_error = await response.json()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 79, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://usapi.gizwits.com/app/bindings')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/bestway/coordinator.py", line 36, in _async_update_data
    await self.api.refresh_bindings()
  File "/config/custom_components/bestway/bestway/api.py", line 140, in refresh_bindings
    device.device_id: device for device in await self._get_devices()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bestway/bestway/api.py", line 145, in _get_devices
    api_data = await self._do_get(f"{self._api_root}/app/bindings")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bestway/bestway/api.py", line 436, in _do_get
    await _raise_for_status(response)
  File "/config/custom_components/bestway/bestway/api.py", line 78, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('https://usapi.gizwits.com/app/bindings')

--

Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.bestway.coordinator
Źródło: custom_components/bestway/coordinator.py:35
integracja: Bestway (dokumentacja, Problemy)
Pierwsze zdarzenie: 26 lipca 2024 14:42:30 (16 zdarzenia)
Ostatnio zalogowany: 08:25:19

Data update failed
Traceback (most recent call last):
  File "/config/custom_components/bestway/coordinator.py", line 37, in _async_update_data
    return await self.api.fetch_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bestway/bestway/api.py", line 168, in fetch_data
    latest_data = await self._do_get(
                  ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bestway/bestway/api.py", line 435, in _do_get
    response = await self._session.get(url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/bestway/coordinator.py", line 35, in _async_update_data
    async with asyncio.timeout(10):
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

**Comment by jelennn** [comment]
For me also a lot of bugs and integration doesn't work after power supply restart:

"Ten błąd pochodzi z niestandardowej integracji.

Rejestrator: custom_components.bestway.coordinator
Źródło: helpers/update_coordinator.py:386
integracja: Bestway (dokumentacja, Problemy)
Pierwsze zdarzenie: 7 sierpnia 2024 22:05:22 (89 zdarzenia)
Ostatnio zalogowany: 12:46:04

Error fetching Bestway API data: Error communicating with API: 502, message='Bad Gateway', url=URL('https://usapi.gizwits.com/app/devdata/hgRr85C9piYANPbdIy6heH/latest')
Error fetching Bestway API data: Error communicating with API:
Error fetching Bestway API data: Error communicating with API: 502, message='Bad Gateway', url=URL('https://usapi.gizwits.com/app/bindings')"

**Comment by cdpuk** [comment]
Unfortunately those 502 errors reflect a problem in the cloud service used by the integration. This is quite common, and there's nothing we can do to fix that. The app is able to communicate using a slightly different method, so you may notice the app still works even when the integration isn't.
